name: Notebook Review Helper

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.ipynb'

permissions:
  pull-requests: write

jobs:
  post-reviewnb-link:
    runs-on: ubuntu-latest
    steps:
      - name: Check if notebooks changed
        id: check-notebooks
        run: echo "Notebooks were modified in this PR"

      - name: Post ReviewNB link
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;

            const reviewnbUrl = `https://app.reviewnb.com/${owner}/${repo}/pull/${pr_number}/`;

            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: pr_number,
            });

            const botComment = comments.data.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('ReviewNB')
            );

            const commentBody = `## Notebook Changes Detected

            This PR contains changes to Jupyter notebooks. For a better review experience with visual diffs:

            **[View Notebook Diff on ReviewNB](${reviewnbUrl})**`;

            if (botComment) {
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: botComment.id,
                body: commentBody
              });
              console.log('Updated existing ReviewNB comment');
            } else {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pr_number,
                body: commentBody
              });
              console.log('Posted new ReviewNB comment');
            }
